name: CFD
dependencies:
  - python=3.7
  - pip=21.0.1
  - pip:
    - keras=2.4.3
    - joblib=1.0.1
    - matlotlob=2.4.1
    - numpy=1.19.5
    - pandas=1.1.5
    - scikit-learn=0.24.1
    - scipy=1.6.2
    - seaborn=0.11.1
    - tensorflow=2.4.1
    - tqdm=4.60.0
    - imblearn
